[platformio]
default_envs = esp32c3_supermini
src_dir = YueXinCat72x40

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = COM21
monitor_port = COM21
monitor_speed = 115200
lib_deps =
  olikraus/U8g2
